CREATE DATABASE GARDENDB;
GO;
USE GARDENDB;
CREATE TABLE GARDEN  (
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    ESPECIE VARCHAR(100),
    VARIEDAD VARCHAR(100),
    NUMERO INT,
    RIEGO VARCHAR(100),
    MULTIPLICAR VARCHAR(100),
    TRANSPLANTAR VARCHAR(100),
    ACLAREO VARCHAR(100),
    METODO VARCHAR(100),
    PODA VARCHAR(100),
    OBSERVACION VARCHAR(100),
    PRIMARY KEY (ID)
);
GO;
